### ISSUE TITLE
About arima parameter m

### ISSUE THREAD

**Issue by peilj** [tgsmith61591/pyramid#19] opened 2017-11-30 08:49 UTC
#### Description
if I want to predict daily data, how to set the arima parameter m ?

**Comment by tgsmith61591** [comment] 2017-11-30 18:37
Depending on the periodicity of your data, it would likely be set to 365. Can't say definitively without knowing your data, though.

Closing issue since it's more of an inquiry.

**Closed by tgsmith61591** 2017-11-30 18:37 UTC

**Comment by peilj** [comment] 2017-12-01 08:06
@tgsmith61591 thank for your reply
I have four years history daily data,  I want to predict the data for the next 90 days by pyramid.
When i used pyramid i don't know how to set the arima parameter m

**Comment by tgsmith61591** [comment] 2017-12-01 11:05
If fitting using auto_arima, you can simply set m=365. If fitting a direct
ARIMA model, the parameter is seasonal_order, and it expects a tuple in the
form of (P, D, Q, m).

http://pyramid-arima.readthedocs.io/en/latest/_submodules/arima.html#auto-arima

**Comment by tgsmith61591** [comment] 2017-12-01 13:30
Also, potential duplicate of #12. If the docs don't solve your issue, take a look at the issue thread and the linked (in the thread) example ipynb.
